const info=[

    {img:"https://domf5oio6qrcr.cloudfront.net/medialibrary/17004/p5-joggingman-n0925-gi2178413162.jpg",url:"https://www.health.harvard.edu/exercise-and-fitness/try-this-warm-up-for-walking-and-running",title:"Try this: Warm-up for walking and running"},
    {img:"https://domf5oio6qrcr.cloudfront.net/medialibrary/16556/p8-bptelehealth-hh0525-gi1454381093.jpg",url:"https://www.health.harvard.edu/heart-health/telehealth-may-help-maintain-healthy-blood-pressure",title:"Telehealth may help maintain healthy blood pressure"},
    {img:"https://domf5oio6qrcr.cloudfront.net/medialibrary/17025/p3-diabetesteam-hl0925-gi2214526209.jpg",url:"https://www.health.harvard.edu/diseases-and-conditions/whos-on-your-diabetes-health-care-team",title:"Who’s on your diabetes health care team?"},
    {img:"https://domf5oio6qrcr.cloudfront.net/medialibrary/16022/h0125h.jpg",url:"https://www.health.harvard.edu/heart-health/teleprehabilitation-reduces-problems-after-heart-surgery",title:`"Teleprehabilitation" reduces problems after heart surgery`},
    {img:"https://img.freepik.com/premium-photo/different-tablets-pills-foil-blister-packs-medications-drugs-blue-background_123211-653.jpg?w=2000",url:"https://www.who.int/news/item/05-09-2025-who-updates-list-of-essential-medicines-to-include-key-cancer--diabetes-treatments",title:"WHO updates list of essential medicines to include key cancer, diabetes treatments"},
    {img:"https://cdn.who.int/media/images/default-source/topics/diseases-and-conditions/cancer/activity-immunizing-against-hpv.tmb-1920v.jpg?sfvrsn=539054e6_1",url:"https://www.who.int/activities/immunizing-against-hpv",title:"Immunizing against HPV"},
    {img:"https://iris.who.int/bitstream/handle/10665/381804/9789240111110-eng.pdf.jpg?sequence=7",url:"https://www.who.int/publications/i/item/9789240111110",title:"WHO guidelines for clinical management of arboviral diseases: dengue, chikungunya, Zika and yellow fever"},
    {img:"https://noorahealth.org/wp-content/uploads/2022/03/og.jpg",url:"https://www.who.int/news/item/29-07-2025-who-and-noora-health-begin-collaboration-to-strengthen-support-for-family-caregivers",title:"WHO and Noora Health begin collaboration to strengthen support for family caregivers"},
    {img:"https://swahsn.com/wp-content/uploads/2022/01/AdobeStock_203325337-scaled.jpeg",url:"https://www.who.int/news/item/09-04-2025-who-maternal-and-perinatal-health-guidelines--easier--faster-and-interactive",title:"WHO maternal and perinatal health guidelines: easier, faster and interactive."},
    {img:"https://tse2.mm.bing.net/th/id/OIP.9udIbm8T3iRt_Y4Arm5lyQHaE8?pid=Api&P=0&h=180",url:"https://www.who.int/news/item/20-11-2024-advancing-access-to-better-paediatric-medicines-on-world-children-s-day",title:"Advancing access to better paediatric medicines on World Children’s Day."},
    {img:"https://tse2.mm.bing.net/th/id/OIP.62aU_dy8bRAilyp97gYGFgHaE8?pid=Api&P=0&h=180",url:"https://www.who.int/news/item/30-06-2025-social-connection-linked-to-improved-heath-and-reduced-risk-of-early-death",title:"Social connection linked to improved health and reduced risk of early death."},
    {img:"https://tse1.mm.bing.net/th/id/OIP.n1x3rZy1VK_hWkIqw-ea5gAAAA?pid=Api&P=0&h=180",url:"https://www.who.int/news/item/13-02-2025-combatting-anaemia-through-improved-measurement-diagnosis-and-reporting",title:"Combatting anaemia through improved measurement, diagnosis and reporting"},

];

module.exports=info;